accounts/urls.py
from accounts.views import register_page, login_page, logout_page
from django.urls import path

app_name = 'accounts'

urlpatterns = [
	path('register/', register_page, name='register'),
	path('login/', login_page, name='login'),
	path('logout/', logout_page, name='logout')
]

crm/urls.py
from crm.views import (
	delete_order, home, dashboard, ProductListView, customer, create_order, update_order, delete_order, user_page, account_settings
)
from django.urls import path

app_name = 'crm'

urlpatterns = [
	path('', home, name='home'),
	path('dashboard/', dashboard, name='dashboard'),
	path('products/', ProductListView.as_view(), name='products'),
	path('customers/<int:pk>/', customer, name='customer'),
	path('order/create/<int:pk>', create_order, name='add_order'),
	path('order/update/<int:pk>', update_order, name='upd_order'),
	path('order/delete/<int:pk>', delete_order, name='del_order'),
	path('user/', user_page, name='userpage'),
	path('account/', account_settings, name='account')
]

divy_crm01/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    path('favicon.ico/', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'))),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('crm.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

crm/models.py
from django.contrib.auth.models import User
from django.db import models

class Customer(models.Model):
	user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
	name = models.CharField(max_length=200, null=True)
	phone = models.CharField(max_length=200, null=True)
	email = models.CharField(max_length=200, null=True)
	picture = models.ImageField(default='profileImg.png', null=True, blank=True)
	date_created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.name

class Tag(models.Model):
	name = models.CharField(max_length=200, null=True)

	def __str__(self):
		return self.name

class Product(models.Model):
	CATEGORIES = (
		('Indoor', 'Indoor'), ('Out door', 'Out door')
	)

	name = models.CharField(max_length=200, null=True)
	price = models.FloatField(null=True)
	category = models.CharField(max_length=200, null=True, choices=CATEGORIES)
	description = models.TextField(null=True, blank=True)
	date_created = models.DateTimeField(auto_now_add=True)
	tags = models.ManyToManyField(Tag)

	def __str__(self):
		return self.name

class Order(models.Model):
	STATUS = (
		('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')
	)

	customer = models.ForeignKey(Customer, related_name='orders', null=True, on_delete=models.SET_NULL)
	product = models.ForeignKey(Product, related_name='orders', null=True, on_delete=models.SET_NULL)
	date_create = models.DateTimeField(auto_now_add=True)
	status = models.CharField(max_length=200, null=True, choices=STATUS)
	note = models.TextField(null=True)

	def __str__(self):
		return f'Order: {self.product.name} '

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

crm/forms.py
from crm.models import Product, Order, Customer
from django.forms import ModelForm

class CustomerForm(ModelForm):
	class Meta:
		model= Customer
		fields = '__all__'
		exclude = ['user']

class OrderForm(ModelForm):
	class Meta:
		model = Order
		fields = '__all__'

accounts/views.py
from django.contrib.auth.forms import AuthenticationForm
from accounts.decorators import unauthenticated_user
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect
from django.contrib.auth.models import Group
from accounts.forms import CreateUserForm
from django.contrib import messages
from crm.models import Customer

@unauthenticated_user
def register_page(request):
	form = CreateUserForm()

	if request.method == 'POST':
		form = CreateUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			username = form.cleaned_data.get('username')
			
			group = Group.objects.get(name='customer')
			user.groups.add(group)
			Customer.objects.create(user=user, name=user.username)
			
			messages.success(request, f'Account created. New user: {username} ')
			return redirect('crm:dashboard')
		else:
			print('Some error')

	context = {
		'form': form
	}
	return render(request, 'accounts/register.html', context)

@unauthenticated_user
def login_page(request):
	form = AuthenticationForm()
	
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			user = form.get_user()
			login(request, user)
			messages.success(request, f'Welcome again {user} ')
			return redirect('crm:dashboard')
		else:
			messages.warning(request, 'Username or password incorrect')
	
	context = {
		'form': form
	}
	return render(request, 'accounts/login.html', context)

def logout_page(request):
	logout(request)
	messages.info(request, 'You have been logged out')
	return redirect('accounts:login')

crm/views.py
from django.contrib.auth.decorators import login_required
from accounts.decorators import admin_only, allowed_users
from django.views.generic import ListView, DetailView
from crm.models import Customer, Order, Product
from django.forms import inlineformset_factory
from django.shortcuts import redirect, render
from crm.forms import OrderForm, CustomerForm
from django.contrib import messages

def home(request):
	return render(request, 'crm/index.html')

@login_required(login_url='accounts:login')
@admin_only
def dashboard(request):
	customers = Customer.objects.all()
	orders = Order.objects.all()
	pendingOrd = Order.objects.filter(status='Pending')
	delivOrd = Order.objects.filter(status='Delivered')

	context = { 
		'customers': customers,
		'orders': orders,
		'pendingOrd': pendingOrd,
		'delivOrd': delivOrd,
	}
	return render(request, 'crm/dashboard.html', context)

class ProductListView(ListView):
	model = Product

@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['customer'])
def user_page(request):
	customer = request.user.customer
	pendingOrd = Order.objects.filter(status='Pending')
	delivOrd = Order.objects.filter(status='Delivered')

	context = {
		'customer': customer,
		'pendingOrd': pendingOrd,
		'delivOrd': delivOrd
	}
	return render(request, 'crm/user_page.html', context)

@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['customer'])
def account_settings(request):
	custmr = request.user.customer
	form = CustomerForm(instance=custmr)

	if request.method == 'POST':
		form = CustomerForm(request.POST, request.FILES, instance=custmr)
		if form.is_valid():
			form.save()
		else:
			messages.warning(request, 'Some field data is incorrect')

	context = {
		'form': form
	}
	return render(request, 'crm/user_settings.html', context)

@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def customer(request, pk):
	customer = Customer.objects.get(id=pk)

	context = {
		'customer': customer
	}
	return render(request, 'crm/customer_detail.html', context)

@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def create_order(request, pk):
	OrderFormSet = inlineformset_factory(Customer, Order, fields=('product', 'status'), extra=8)

	customer = Customer.objects.get(id=pk)
	formset = OrderFormSet(queryset=Order.objects.none(), instance=customer)
	#form = OrderForm(initial={'customer':customer})

	if request.method == 'POST':
		formset = OrderFormSet(request.POST, instance=customer)
		if formset.is_valid():
			formset.save()
			return redirect('crm:dashboard')

	context = {
		'formset': formset
	}
	return render(request, 'crm/order_form.html', context)

@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def update_order(request, pk):
	order = Order.objects.get(id=pk)
	form = OrderForm(instance=order)

	if request.method == 'POST':
		form = OrderForm(request.POST, instance=order)
		if form.is_valid():
			form.save()
			return redirect('crm:dashboard')

	context = {
		'order': order,
		'form': form
	}
	return render(request, 'crm/order_form.html', context)

@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def delete_order(request, pk):
	order = Order.objects.get(id=pk)

	if request.method == 'POST':
		order.delete()
		return redirect('crm:dashboard')

	context = {
		'order': order
	}
	return render(request, 'crm/order_delete.html', context)

accounts/templates/accounts/login.html
{% extends 'base.html' %}
<!-- . -->
{% block title %} Register {% endblock %}
<!-- . -->
{% block main %}
<!-- . -->
<div class="frm-box">
   <h1>Access to your account</h1>
   <form method="post">
      {% csrf_token %}
      <!-- . -->
      {% for field in form %}
      <!-- . -->
      {{ field.label }}
      <!-- . -->
      {{ field}}
      <!-- . -->
      {% endfor %}
      <!-- . -->
      <button type="submit">Login</button>
   </form>
</div>
<div class="extra">
   <p>
      Don't have an account yet.
      <a href="{% url 'accounts:register' %}">Register</a>
   </p>
</div>
<!-- . -->
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
<!-- . -->
{% block title %} Register {% endblock %}
<!-- . -->
{% block main %}
<!-- . -->
<div class="frm-box">
   <h1>Create an account</h1>
   <form method="post">
      {% csrf_token %}
      <!-- . -->
      {% for field in form %}
      <!-- . -->
      {{ field.label }}
      <!-- . -->
      {{ field }}
      <!-- . -->
      {% endfor %}
      <button type="submit">Create</button>
   </form>
</div>
<div class="extra">
   <p>
      Already have an account. <a href="{% url 'accounts:login' %}">Login</a>
   </p>
</div>
<!-- . -->
{% endblock %}

crm/templates/crm/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <link rel="icon" href="{% static 'favicon.ico' %}" />
      <link rel="stylesheet" href="{% static 'css/main.css' %} " />
      <title>{% block title %}{% endblock %} | CRM</title>
   </head>
   <body>
      <header>
         <nav>
            <ul>
               <li>
                  <a href="{% url 'crm:home' %} " class="logo">CRM APP </a>
               </li>
               <li><a href="{% url 'crm:home' %} ">Home</a></li>
               <li><a href="{% url 'crm:dashboard' %} ">Dashboard</a></li>
               <li><a href="{% url 'crm:products' %} ">Products</a></li>
            </ul>
            <ul>
               {% if user.is_authenticated %}
               <li><a href="{% url 'crm:logout' %}">Logout</a></li>
               {% else %}
               <li><a href="{% url 'crm:login' %}">Login </a></li>
               <li><a href="{% url 'crm:register' %}">Register</a></li>
               {% endif %}
            </ul>
         </nav>
      </header>
      <div class="msgs">
         {% for msg in messages %}
         <p>{{msg}}</p>
         {% endfor %}
      </div>
      <main>{% block main %} {% endblock %}</main>
   </body>
</html>

crm/templates/crm/customer_detail.html
{%extends 'base.html' %}
<!-- . -->
{% block title %}Customer{% endblock %}
<!-- . -->
{% block main %}
<section class="cards">
   <article class="card card-1">
      <h4>Customer</h4>
      <a href="{% url 'crm:add_order' customer.id %}" class="btnU"
         >Place New Order</a
      >
      <a href="" class="btnU">Update Customer</a>
      <a href="" class="btnD">Delete Customer</a>
   </article>
   <article class="card card-2">
      <h4>Contact Information</h4>
      <p><span> Name:</span> {{ customer.name }}</p>
      <p><span> Email:</span> {{ customer.email }}</p>
      <p><span> Phone:</span> {{ customer.phone }}</p>
   </article>
   <article class="card card-3">
      <h4>Total Orders</h4>
      <p>{{ customer.orders.all|length }}</p>
   </article>
</section>
<article class="table">
   <h3>{{ customer.name }}'s Orders:</h3>
   <div class="box">
      <ul class="lst-cdet">
         <li>
            <p>Product</p>
            <p>Category</p>
            <p>Date ordered</p>
            <p>Status</p>
            <p>Update</p>
            <p>Remove</p>
         </li>
         {% for order in customer.orders.all %}
         <li>
            <p>{{ order.product.name }}</p>
            <p>{{ order.product.category }}</p>
            <p>{{ order.date_create|date:'Y-M-d' }}</p>
            <p>{{ order.status }}</p>
            <a href="{% url 'crm:upd_order' order.id %}" class="btnUpd"
               >Update</a
            >
            <a href="{% url 'crm:del_order' order.id %}" class="btnDel"
               >Remove</a
            >
         </li>
         {% endfor %}
      </ul>
   </div>
</article>
{% endblock %}

crm/templates/crm/dashboard.html
{%extends 'base.html' %}
<!-- . -->
{% block title %}Dashboard{% endblock %}
<!-- . -->
{% block main %}
<section class="status">
   <div class="box">
      <p class="head">Total Orders</p>
      <p>{{ orders|length }}</p>
   </div>
   <div class="box">
      <p class="head">Orders Delivered</p>
      <p>{{ delivOrd|length }}</p>
   </div>
   <div class="box">
      <p class="head">Orders Pending</p>
      <p>{{ pendingOrd|length }}</p>
   </div>
</section>
<section class="dash">
   <article class="table">
      <h3>Customers:</h3>
      <div class="box">
         <a href="" class="btnAdd">Create Customer</a>
         <ul class="lst-cust">
            <li>
               <p>View</p>
               <p>Customer</p>
               <p>Orders</p>
            </li>
            {% for customer in customers %}
            <li>
               <a href="{% url 'crm:customer' customer.id %}" class="btnView"
                  >View</a
               >
               <p>{{ customer.name }}</p>
               <p>{{ customer.orders.all|length }}</p>
            </li>
            {% endfor %}
         </ul>
      </div>
   </article>
   <article class="table">
      <h3>Last 5 Orders</h3>
      <div class="box">
         <a href="" class="btnAdd">Create Order</a>
         <ul class="lst-ord">
            <li>
               <p>Product</p>
               <p>Date Ordered</p>
               <p>Status</p>
               <p>Update</p>
               <p>Remove</p>
            </li>
            {% for order in orders %}
            <li>
               <p>{{ order.product.name }}</p>
               <p>{{ order.date_create|date:'Y-M-d' }}</p>
               <p>{{ order.status }}</p>
               <a href="{% url 'crm:upd_order' order.id %}" class="btnUpd"
                  >Update</a
               >
               <a href="{% url 'crm:del_order' order.id %}" class="btnDel"
                  >Remove</a
               >
            </li>
            {% endfor %}
         </ul>
      </div>
   </article>
</section>
{% endblock %}

crm/templates/crm/index.html
{% extends 'base.html' %}
<!-- . -->
{% block title %} Index {% endblock %}
<!-- . -->
{% block main %}
<!-- . -->
<h1>Client Relationship Management with Django</h1>
<!-- . -->
{% endblock %}

crm/templates/crm/login.html
{% extends 'crm/base.html' %}
<!-- . -->
{% block title %} Register {% endblock %}
<!-- . -->
{% block main %}
<!-- . -->
<div class="frm-box">
   <h1>Access to your account</h1>
   <form method="post">
      {% csrf_token %}
      <!-- . -->
      {% for field in form %}
      <!-- . -->
      {{ field.label }}
      <!-- . -->
      {{ field}}
      <!-- . -->
      {% endfor %}
      <!-- . -->
      <button type="submit">Login</button>
   </form>
</div>
<div class="extra">
   <p>
      Don't have an account yet. <a href="{% url 'crm:register' %}">Register</a>
   </p>
</div>
<!-- . -->
{% endblock %}

crm/templates/crm/order_delete.html
{%extends 'base.html' %}
<!-- . -->
{% block title %}Delete Order{% endblock %}
<!-- . -->
{% block main %}
<p>Are you sure you want to delete {{order.product.name}}</p>
<form method="post">
   {% csrf_token %}
   <a href="{% url 'crm:dashboard' %}">Cancel</a>
   <button type="submit">Delete</button>
</form>
{% endblock %}

crm/templates/crm/order_form.html
{%extends 'base.html' %}
<!-- . -->
{% block title %}Order{% endblock %}
<!-- . -->
{% block main %}
<form method="post">
   {% csrf_token %}
   <!-- . -->
   {% for form in formset %}
   <!-- . -->
   {{ formset.management_form }}
   <!-- . -->
   {{ form }}<br />
   <!-- . -->
   {% endfor %}
   <button type="submit">Create</button>
</form>
{% endblock %}

crm/templates/crm/product_list.html
{%extends 'base.html' %}
<!-- . -->
{% block title %}Products{% endblock %}
<!-- . -->
{% block main %}
<article class="table">
   <h3>All Products:</h3>
   <div class="box">
      <ul class="lst-prod">
         <li>
            <p>Product</p>
            <p>Price</p>
            <p>Category</p>
         </li>
         {% for product in product_list %}
         <li>
            <p>{{ product.name }}</p>
            <p>{{ product.price }}</p>
            <p>{{ product.category }}</p>
         </li>
         {% endfor %}
      </ul>
   </div>
</article>
{% endblock %}

crm/templates/crm/register.html
{% extends 'crm/base.html' %}
<!-- . -->
{% block title %} Register {% endblock %}
<!-- . -->
{% block main %}
<!-- . -->
<div class="frm-box">
   <h1>Create an account</h1>
   <form method="post">
      {% csrf_token %}
      <!-- . -->
      {% for field in form %}
      <!-- . -->
      {{ field.label }}
      <!-- . -->
      {{ field }}
      <!-- . -->
      {% endfor %}
      <button type="submit">Create</button>
   </form>
</div>
<div class="extra">
   <p>Already have an account. <a href="{% url 'crm:login' %}">Login</a></p>
</div>
<!-- . -->
{% endblock %}

crm/templates/crm/user_page.html
{%extends 'base.html' %}
<!-- . -->
{% block title %}User Page{% endblock %}
<!-- . -->
{% block main %}
<section class="status">
   <div class="box">
      <p class="head">Total Orders</p>
      <p>{{ customer.orders.all|length }}</p>
   </div>
   <div class="box">
      <p class="head">Orders Delivered</p>
      <p>{{ delivOrd|length }}</p>
   </div>
   <div class="box">
      <p class="head">Orders Pending</p>
      <p>{{ pendingOrd|length }}</p>
   </div>
</section>
<article class="table">
   <h3>{{ customer.name }}'s Orders:</h3>
   <div class="box">
      <ul class="lst-cdet">
         <li>
            <p>Product</p>
            <p>Category</p>
            <p>Date ordered</p>
            <p>Status</p>
            <p>Update</p>
            <p>Remove</p>
         </li>
         {% for order in customer.orders.all %}
         <li>
            <p>{{ order.product.name }}</p>
            <p>{{ order.product.category }}</p>
            <p>{{ order.date_create|date:'Y-M-d' }}</p>
            <p>{{ order.status }}</p>
            <a href="{% url 'crm:upd_order' order.id %}" class="btnUpd"
               >Update</a
            >
            <a href="{% url 'crm:del_order' order.id %}" class="btnDel"
               >Remove</a
            >
         </li>
         {% endfor %}
      </ul>
   </div>
</article>
{% endblock %}

crm/templates/crm/user_settings.html
{%extends 'base.html' %}
<!-- . -->
{% block title %}User Settings{% endblock %}
<!-- . -->
{% block main %}
<section class="account">
   <article class="pic">
      <a href="{% url 'crm:userpage' %}" class="btn">Back to profile</a>
      <div class="box">
         <h3>Account Settings</h3>
         <img src="{{ request.user.customer.picture.url}} " alt="" />
      </div>
   </article>
   <article class="info">
      <h3>User Information</h3>
      <form method="post" enctype="multipart/form-data">
         {% csrf_token %}
         <!-- . -->
         {% for field in form %}
         <!-- . -->
         {{ field.label }}
         <!-- . -->
         {{ field}}
         <!-- . -->
         <!-- . -->
         <!-- . -->

         {% endfor %}
         <!-- . -->
         <button type="submit">Update</button>
      </form>
   </article>
</section>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <link rel="icon" href="{% static 'favicon.ico' %}" />
      <link rel="stylesheet" href="{% static 'css/main.css' %} " />
      <title>{% block title %}{% endblock %} | CRM</title>
   </head>
   <body>
      <header>
         <nav>
            <ul>
               <li>
                  <a href="{% url 'crm:home' %} " class="logo">CRM APP </a>
               </li>
               <li><a href="{% url 'crm:home' %} ">Home</a></li>
               {% if request.user.is_staff %}
               <li><a href="{% url 'crm:dashboard' %} ">Dashboard</a></li>
               <li><a href="{% url 'crm:products' %} ">Products</a></li>
               {% else %}
               <li><a href="{% url 'crm:account' %}">Account</a></li>
               {% endif %}
            </ul>
            <ul>
               {% if user.is_authenticated %}
               <li><a href="" class="no-a">{{ user.username }} </a></li>
               <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
               {% else %}
               <li><a href="{% url 'accounts:login' %}">Login </a></li>
               <li><a href="{% url 'accounts:register' %}">Register</a></li>
               {% endif %}
            </ul>
         </nav>
      </header>
      <div class="msgs">
         {% for msg in messages %}
         <p>{{msg}}</p>
         {% endfor %}
      </div>
      <main>{% block main %} {% endblock %}</main>
   </body>
</html>